base/urls.py
from django.urls import path
from .views import *

app_name="base"
urlpatterns = [
    path('home/', HomeTemplateView.as_view(), name='home'),
    path('message/', send_message, name="message")
]

portfolio/urls.py
from django.contrib import admin
from django.shortcuts import redirect
from django.urls import path, include

from django.conf.urls.static import static
from django.conf import settings



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', lambda x : redirect('base:home', permanent=False)),
    path('portfolio/', include('base.urls')),
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

base/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.core.validators import MinValueValidator, MaxValueValidator
from phonenumber_field.modelfields import PhoneNumberField

# Create your models here.
class Owner(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    short_description = models.TextField(null=True)
    title = models.CharField(max_length=100)
    description = models.TextField(null=True)
    profile_picture = models.ImageField(upload_to="images/about", null=True)
    cover_picture = models.ImageField(upload_to="images/about", null=True)
    name = lambda self: f"{self.user.first_name} {self.user.last_name}"
    cv = models.FileField("Curriculum Vitae", upload_to="document/owner", blank=True, null=True)
    phone_number = PhoneNumberField(blank=True, null=True)
    location = models.CharField(max_length=100)
    class Meta:
        verbose_name = "About me"
        verbose_name_plural = "About me"
    def current_name(self):
        return self.user.first_name.split()[-1] or ''
    def __str__(self) -> str:
        return f"{self.user.first_name} {self.user.last_name}"

class AbstractAbout(models.Model):
    owner = models.ForeignKey(Owner, on_delete=models.CASCADE)
    title = models.CharField(max_length=100)
    
    class Meta:
        abstract=True

    def __str__(self):
        return self.title
class AbstractWithLogo(AbstractAbout):
    class_logo = models.CharField(max_length=50)
    class Meta:
        abstract=True
class Skill(AbstractWithLogo):
    pass
    
    

class SkillDetail(models.Model):
    skill = models.ForeignKey(Skill, on_delete=models.CASCADE)
    name = models.CharField(max_length=100)
    level = models.IntegerField(
        default=50, 
        validators=[
            MaxValueValidator(100),
            MinValueValidator(1)
        ]
    )
    def __str__(self):
        return f"{self.skill} - {self.name}"
    
class Qualification(AbstractWithLogo):
    pass

class QualificationDetail(models.Model):
    qualification = models.ForeignKey(Qualification, on_delete=models.CASCADE)
    start = models.DateField()
    end = models.DateField(null=True, blank=True)
    name = models.CharField(max_length=100)
    detail = models.CharField(max_length=100)
    
    def duration(self):
        end = f"- {self.end.strftime('%m/%Y')}" if self.end else ''
        return f"{self.start.strftime('%m/%Y')} {end}"
    def __str__(self):
        return f"{self.qualification} - {self.name}"
        
class Service(AbstractWithLogo):
    pass

class ServiceDetail(models.Model):
    service = models.ForeignKey(Service, on_delete=models.CASCADE)
    description = models.CharField("Service name",max_length=100)
    
    def __str__(self):
        return f"{self.service} - {self.description}"
    
class Project(AbstractAbout):
    link = models.URLField()
    description = models.TextField()
    image = models.ImageField(upload_to='images/projects', null=True)
    source = models.URLField()
    detail = models.URLField()

    def __str__(self):
        return self.title

class SocialMediaContact(AbstractAbout):
    link = models.URLField(blank=True, null=True)
    pseudo = models.CharField("name",max_length=100)
    class_logo = models.CharField(max_length=50)
    
class Message(models.Model):
    name = models.CharField(max_length=100)
    title = models.CharField(max_length=100)
    email = models.EmailField()
    message = models.TextField(null=False, blank=False)
    def __str__(self):
        return f"{self.title} - {self.name}"

base/forms.py
from django import forms
from .models import Message
class MessageForm(forms.ModelForm):
    name = forms.CharField(max_length=100, widget=forms.TextInput(attrs={'class': "contact__input"}))
    title = forms.CharField(max_length=100, widget=forms.TextInput(attrs={'class': "contact__input"}))
    email = forms.EmailField(widget=forms.TextInput(attrs={'class': "contact__input"}))
    message = forms.CharField(widget=forms.Textarea(attrs={'cols':"0",'rows':"7", 'class': "contact__input"}))
    class Meta:
        model = Message
        fields = ('name', 'title', 'email', 'message', )

base/views.py
from typing import Any
from django.http import BadHeaderError
from django.shortcuts import redirect, render
from django.views.generic import TemplateView
from .models import Owner
from .forms import MessageForm
from django.core.mail import send_mail
from django.contrib import messages
# Create your views here.

class HomeTemplateView(TemplateView):
    template_name = "base/index.html"
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["owner"] = Owner.objects.all()[0]
        context['form'] = MessageForm()
        return context
    
def send_message(request):
    if request.method == "POST":
        form = MessageForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, "Message sent")
        else:
            messages.error(request, "Something went wrong. Please try again.")
    else:
        messages.error(request, "Something went wrong. Please try again.")
            
    return redirect("base:home")

templates/base/includes/about.html
<section class="about section" id="about">
    <h2 class="section__title">About me</h2>
    <span class="section__subtitle">My introduction</span>

    <div class="about__container container grid">
        <img src="{{owner.cover_picture.url}}" alt="Me" class="about__img">
        <div class="about__data">
            <p class="about__description">{{owner.description}}</p>
            <div class="about__buttons">
                <a href="{{owner.cv.url}}" download="" class="button button--flex">
                    Download CV <i class="uil uil-download-alt button-icon"></i>
                </a>
            </div>
        </div>
    </div>
</section>

templates/base/includes/contact.html
<section class="contact section" id="contact">
    <h2 class="section__title">Contact me</h2>
    <span class="section__subtitle">Get in touche</span>
    <div class="contact__container container grid">
        <div>
            <h3 class="descr-title">My contact</h3>
            <div class="contact__information">
                <i class="contact__icon uil uil-phone"></i>
                <div>
                    <h3 class="contact__title">Phone number</h3>
                    <span class="contact__subtitle">{{owner.phone_number|default:""}}</span>
                </div>
            </div>

            <div class="contact__information">
                <i class="contact__icon uil uil-envelope"></i>
                <div>
                    <h3 class="contact__title">Email</h3>
                    <span class="contact__subtitle">{{owner.user.email|default:""}}</span>
                </div>
            </div>

            <div class="contact__information">
                <i class="contact__icon uil uil-map-marker"></i>
                <div>
                    <h3 class="contact__title">Location</h3>
                    <span class="contact__subtitle">{{owner.location|default:""}}</span>
                </div>
            </div>
            
            {% for contact in owner.socialmediacontact_set.all %}
                <div class="contact__information">
                    <i class="contact__icon uil uil-{{contact.class_logo}}"></i>
                    <div>
                        <h3 class="contact__title">{{contact.title}}</h3>
                        {% if contact.link %}
                            <a href="{{contact.link}}" target="_blank">
                        {% endif %}
                        <span class="contact__subtitle">{{contact.pseudo|default:""}}</span>
                        {% if contact.link %}
                            </a>
                        {% endif %}
                    </div>
                </div>
            {% endfor %}
        </div>
        <form action="{% url 'base:message' %}" class="contact__form grid" method="POST">
            {% csrf_token %}
            <h3 class="descr-title">Leave me a message directely</h3>
            <div class="contact__inputs grid">
                <div class="contact__content">
                    <label class="contact__label">
                        Name
                        {{form.name}}
                    </label>

                </div>
                <div class="contact__content">
                    <label class="contact__label">
                        Object
                        {{form.title}}
                    </label>

                </div>
                <div class="contact__content">
                    <label class="contact__label">
                        Email
                        {{form.email}}
                    </label>

                </div>
            </div>
            <div class="contact__content">
                <label class="contact__label">
                    Message
                    {{form.message}}
                </label>
            </div>
            <div>
                <button type="submit" class="button button--flex">
                    Send Message <i class="button__icon uil uil-message"></i>
                </button>
            </div>
        </form>
    </div>
</section>

templates/base/includes/footer.html
<div class="footer__bg">
    <div class="footer__container container grid">
        <div>
            <h1 class="footer__title">{{owner.user.first_name}}</h1>
            <span class="footer__subtitle">{{owner.title}}</span>
        </div>
        <ul class="footer__links">
            <li>
                <a href="#services" class="footer__link">Services</a>
            </li>
            <li>
                <a href="#projects" class="footer__link">projects</a>
            </li>
            <li>
                <a href="#contact" class="footer__link">Contact</a>
            </li>
        </ul>
        <div class="footer__socials">
            {% if owner.facebook %}
                <a href="{{owner.facebook}}" class="footer__social" target="_blank">
                    <i class="uil uil-facebook"></i>
                </a>
            {% endif %}
            {% if owner.github %}
                <a href="{{owner.github}}" class="footer__social"  target="_blank">
                    <i class="uil uil-github"></i>
                </a>
            {% endif %}
            {% if owner.linkedin %}
                <a href="{{owner.linkedin}}" class="footer__social"  target="_blank">
                    <i class="uil uil-linkedin"> </i>
                </a>
            {% endif %}
            
        </div>
    </div>
</div>

templates/base/includes/header.html
{% load static %}
<header class="header" id="header">
    <nav class="nav container">
        <a href="#" class="nav__logo">{{owner.current_name|capfirst}}</a>
        <div class="nav__menu" id="nav-menu">
            <ul class="nav__list grid">
                <li>
                    <a href="#home" class="nav__link active-link">
                        <i class="uil uil-home nav__icon"></i>Home
                    </a>
                </li>
                <li>
                    <a href="#about" class="nav__link">
                        <i class="uil uil-user nav__icon"></i>About
                    </a>
                </li>
                <li>
                    <a href="#skills" class="nav__link">
                        <i class="uil uil-brain nav__icon"></i>Skills
                    </a>
                </li>
                <li>
                    <a href="#qualification" class="nav__link">
                        <i class="uil uil-file-alt nav__icon"></i>Qualification
                    </a>
                </li>
                <li>
                    <a href="#services" class="nav__link">
                        <i class="uil uil-briefcase-alt nav__icon"></i>Services
                    </a>
                </li>
                <li>
                    <a href="#projects" class="nav__link">
                        <i class="uil uil-scenery nav__icon"></i>projects
                    </a>
                </li>
                <li>
                    <a href="#contact" class="nav__link">
                        <i class="uil uil-message nav__icon"></i>Contact me
                    </a>
                </li>
            </ul>
            <i class="uil uil-times nav__close" id="nav-close"></i>
        </div>
        <div class="nav__btns">

            <i class="uil change-theme uil-moon" id="theme-button"></i>
            <div class="nav__toggle" id="nav-toggle">
                <i class="uil uil-apps"></i>
            </div>
        </div>
        
    </nav>
</header>

templates/base/includes/home.html
{% load static %}
<section class="section" id="home">
    <div class="home__container container grid">
        <div class="home__content grid">
            <div class="home__social">
                <a href="#" target="_blank" class="home__social-icon">
                    <i class="uil uil-linkedin-alt"></i>
                </a>
                <a href="#" target="_blank" class="home__social-icon">
                    <i class="uil uil-dribbble"></i>
                </a>
                <a href="#" target="_blank" class="home__social-icon">
                    <i class="uil uil-github-alt"></i>
                </a>
            </div>
            <div class="home__img">
                <svg class="home__blob" viewBox="0 0 200 187" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
                    <mask id="mask0" mask-type="alpha">
                        <path d="M190.312 36.4879C206.582 62.1187 201.309 102.826 182.328 134.186C163.346 165.547 
                        130.807 187.559 100.226 186.353C69.6454 185.297 41.0228 161.023 21.7403 129.362C2.45775 
                        97.8511 -7.48481 59.1033 6.67581 34.5279C20.9871 10.1032 59.7028 -0.149132 97.9666 
                        0.00163737C136.23 0.303176 174.193 10.857 190.312 36.4879Z"/>
                    </mask>
                    <g mask="url(#mask0)">
                        <path d="M190.312 36.4879C206.582 62.1187 201.309 102.826 182.328 134.186C163.346 
                        165.547 130.807 187.559 100.226 186.353C69.6454 185.297 41.0228 161.023 21.7403 
                        129.362C2.45775 97.8511 -7.48481 59.1033 6.67581 34.5279C20.9871 10.1032 59.7028 
                        -0.149132 97.9666 0.00163737C136.23 0.303176 174.193 10.857 190.312 36.4879Z"/>
                        <image class="home__blob-img" x="15" href="{{owner.profile_picture.url}}"/>
                    </g>
                </svg>
            </div>
            <div class="home__data">
                <h1 class="home__title">Hi,  I'm {{owner.current_name|title}}</h1>
                <h3 class="home__subtitle">{{owner.title|title}}</h3>
                <p class="home__description">{{owner.short_description|capfirst}}</p>
                <a href="#contact" class="button button--flex">
                    Contact me<i class="uil uil-message button__icon"></i>
                </a>
            </div>
        </div>
    </div>
</section>

templates/base/includes/project.html
<section class="projects section" id="projects">
    <h2 class="section__title">projects</h2>
    <span class="section__subtitle">Most recent work</span>

    <div class="projects__container container">
        <div>
            
            {% for project in owner.project_set.all %}
                <div class="projects__content grid">
                    <a href="{{project.link}}" target='_blank'>
                        <img src="{{project.image.url}}" alt="{{projects.title}}" class="projects__img">
                    </a>

                    <div class="projects__data">
                        <h3 class="projects__title">{{project.title}}</h3>
                        <p class="projects-description">{{project.description}}</p>
                    </div>
                    <span class="button button--flex button--small button--link services__button">
                        View more <i class="button__icon uil uil-arrow-right"></i>
                    </span>
                    <div class="services__modal">
                        <div class="projects-modal">
                            <i class="services__modal-close uil uil-times"></i>
                            <div class="links-project-modal">
                                <div class='project-image-modal'>
                                    <a href="{{project.link}}" target='_blank'>
                                        <img src="{{project.image.url}}" alt="{{project.title}}">
                                    </a>
                                </div>
                                <div class="projects-sources-modal">
                                    <div class="projects-link-modal"><a href="{{project.link}}" target='_blank'>View site <i class="button__icon uil uil-arrow-right"></i></a></div>
                                    <div class="projects-link-modal"><a href="{{project.source}}" target='_blank'>Source code <i class="button__icon uil uil-arrow-right"></i></a></div>
                                    <div class="projects-link-modal"><a href="{{project.detail}}" target='_blank'>Detail <i class="button__icon uil uil-arrow-right"></i></a></div>
                                </div>
                                
                            </div>
                            <div class="projects-details-modal">
                                <h2 class="projects-title-modal">Title : {{project.title}}</h3>
                                <h3 class="project-subtitle-modal">Description</h3>
                                <div class="project-description-modal">
                                    {{project.description}}
                                </div>
                                
                            </div>
                        </div>

                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
</section>

templates/base/includes/projects.html
<section class="projects section" id="projects">
    <h2 class="section__title">projects</h2>
    <span class="section__subtitle">Most recent work</span>

    <div class="projects__container container">
        <div>
            
            {% for projects in owner.projects_set.all %}
                <div class="projects__content grid swiper-slide">
                    <a href="{{projects.link}}" target='_blank'>
                        <img src="{{projects.image.url}}" alt="{{projects.title}}" class="projects__img">
                    </a>

                    <div class="projects__data">
                        <h3 class="projects__title">{{projects.title}}</h3>
                        <p class="projects__description">{{projects.description}}</p>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
</section>

templates/base/includes/qualifications.html
<section class="skills section" id="qualification">
    <h2 class="section__title">Qualifications</h2>
    <span class="section__subtitle">professionnal career</span>

    <div class="container grid skills__container">
        
        {% for qualification in owner.qualification_set.all %}
            <div class="skills__content skills__close">
                <div class="skills__header">
                    <i class="uil uil-{{qualification.class_logo}} skills__icon"></i>
                    <div>
                        <h1 class="skills__title">{{qualification.title|title}}</h1>
                    </div>
                    <i class="uil uil-angle-down skills__arrow"></i>
                </div>
                <div class="skills__list grid">
                    {% for qualification_detail in qualification.qualificationdetail_set.all reversed %}
                        <div class="skills__data">
                            <h2 class="qualification__title">{{qualification_detail.title|title}}</h2>
                            <h3 class="qualification__title">{{qualification_detail.name|title}}</h3>
                            <span class="qualification__subtitle">{{qualification_detail.detail|capfirst}}</span>
                            <div class="qualification__calendar">
                                <i class="uil uil-calendar-alt"></i>{{qualification_detail.duration}}
                            </div>
                        </div>
                    {% endfor %}
                </div>
            </div>
        {% endfor %}
    </div>
</section>

templates/base/includes/services.html
<section class="services section" id="services">
    <h2 class="section__title">Services</h2>
    <span class="section__subtitle">What I offer</span>
    <div class="services__container container grid">
        {% for service in owner.service_set.all %}
            <div class="services__content">
                <div>
                    <i class="services__icon uil uil-{{service.class_logo}}"></i>
                    <h3 class="service__title">{{service.title|title}}</h3>
                </div>
                <span class="button button--flex button--small button--link services__button">
                    View more <i class="button__icon uil uil-arrow-right"></i>
                </span>
                <div class="services__modal">
                    <div class="services__modal-content">
                        <h4 class="services__modal-title">{{service.title|title}}</h4>
                        <i class="services__modal-close uil uil-times"></i>
                    
                        <ul class="services__modal-services grid">
                            
                            {% for service_detail in service.servicedetail_set.all %}
                                <li class="services__modal-service">
                                    <p>
                                        <i class="uil uil-check-circle services__modal-icon"></i>{{service_detail.description|capfirst}}
                                    </p>
                                </li> 
                            {% endfor %}
                        </ul>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
</section>

templates/base/includes/skills.html
<section class="skills section" id="skills">
    <h2 class="section__title">Skills</h2>
    <span class="section__subtitle">My techmical level</span>

    <div class="container grid skills__container">
        
        {% for skill in owner.skill_set.all %}
            <div class="skills__content skills__close">
                <div class="skills__header">
                    <i class="uil uil-{{skill.class_logo}} skills__icon"></i>
                    <div>
                        <h1 class="skills__title">{{skill.title|title}}</h1>
                        <span class="skills__subtitle">{{skill.duration}}</span>
                    </div>
                    <i class="uil uil-angle-down skills__arrow"></i>
                </div>
                <div class="skills__list grid">
                    
                    {% for skill_detail in skill.skilldetail_set.all %}
                        <div class="skills__data">
                            <div class="skills__title">
                                <h3 class="skills__name">{{skill_detail.name|title}}</h3>
                                <span class="skills__number">{{skill_detail.level}}%</span>
                            </div>
                            <div class="skills__bar">
                                <span class="skills__percentage skills__html" style="width:{{skill_detail.level}}%"></span>
                            </div>
                        </div>
                    {% endfor %}
                </div>
            </div>
        {% endfor %}
    </div>
</section>

templates/base/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    
    <!-- SEO Meta Tags -->
    <meta name="description" content="I am a web developper and this is my port folio">
    <meta name="author" content="ANDRIAMIFIDISOA Nomena Sombiniaina Alfa">


    <!-- Webpage Title -->
    <title>Personnal Portfolio</title>
    
    <!-- Styles -->
	<link rel="stylesheet" href="https://unicons.iconscout.com/release/v4.0.8/css/line.css">
    <link rel="stylesheet" href="{% static 'base/css/swiper-bundle.min.css' %}">
	<link href="{% static 'base/css/styles.css' %}" rel="stylesheet">

	<!-- Favicon  -->
    <link rel="icon" href="{% static 'base/images/favicon.png' %}">
</head>
<body>
    <header class="header" id="header">
        {% include 'base/includes/header.html' %}
    </header>
    <main class="main">
        {% if messages %}
            <div id="messages">
                {% for message in messages %}
                    <div class="alert alert-{{ message.tags }}">{{ message }}</div>
                {% endfor %}
            </div>
        {% endif %}       

        {% include 'base/includes/home.html' %}

        {% include 'base/includes/about.html' %}

        {% include 'base/includes/skills.html' %}

        {% include 'base/includes/qualifications.html' %}

        {% include 'base/includes/services.html' %}

        {% include 'base/includes/project.html' %}
        
        {% include 'base/includes/contact.html' %}

    </main>
    <footer class="footer">
        {% include 'base/includes/footer.html' %}
    </footer>
    <!-- Scripts -->
    <script src="{% static 'base/js/swiper-bundle.min.js' %}"></script>
    <script src="{% static 'base/js/scripts.js' %}"></script>
</body>
</html>